spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
server:
  port: 8080
mybatis: #开启Mybatis下划线命名转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
      
