spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 118.190.71.215
    port: 6379
  session:
    store-type: redis ##session共享采用redis来存储 
    
server:
  port: 8080
  servlet:
    session:
      timeout: 65  # session 过期时间，单位：秒
mybatis: #开启Mybatis下划线命名转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
      
